<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML32586" name="Com.Test_Classes.Design_Pattern_Test" tests="2" failures="1" timestamp="21 Jan 2020 05:32:52 GMT" time="54.354" errors="0">
  <testcase name="orgbImmersiveAurora" time="38.610" classname="Com.Test_Classes.Design_Pattern_Test"/>
  <testcase name="orgatakeSrcImageCES" time="15.744" classname="Com.Test_Classes.Design_Pattern_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Launched Url is not same expected [https://peoplehub.mindtree.com/Pages/OrgCanvas.aspx] but found [https://peoplehub.mindtree.com/Pages/OrgCanvas.aspxghshgs]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:Launched Url is not same expected [https://peoplehub.mindtree.com/Pages/OrgCanvas.aspx] but found [https://peoplehub.mindtree.com/Pages/OrgCanvas.aspxghshgs]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at Com.Test_Classes.Design_Pattern_Test.orgatakeSrcImageCES(Design_Pattern_Test.java:114)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- orgatakeSrcImageCES -->
</testsuite> <!-- Com.Test_Classes.Design_Pattern_Test -->
